package dev.gihan.movieapi.model.option;

public enum Genre {
    ACTION, COMEDY, DRAMA, HORROR, THRILLER, ROMANCE,
    SCIENCE_FICTION, FANTASY, DOCUMENTARY, ANIMATION,
    MYSTERY, CRIME, ADVENTURE, FAMILY, MUSICAL, WAR,
    WESTERN, BIOGRAPHY, HISTORY, SPORT
}
